version: "3.9"
services:
  vue_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Mapping port 3000 di host ke port 80 di container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
